theme: minima
title: Coffee
author: Random student
email: hthom5@ocdsb
description: > # this means to ignore newlines until "baseurl:"
  I like coffee, you like coffee, we all like coffee. So why not make a blog about it

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
